### ISSUE TITLE
Duplicate keys

### ISSUE THREAD

**Issue by joelwking** [nsthompson/ansible-collection-dependencies#2]
When using a playbook with duplicate variable names, as:
```
#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2019 World Wide Technology, Inc.
#      All rights reserved.
#
#      author: Joel W. King, World Wide Technology
#
#      usage: ./test_xls.yml -e 'dest=/tmp/' --tags play2
#
#  ------
#  Play 1
#  ------
- hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - '{{ playbook_dir }}/files/passwords.yml'
  vars:
   tet:
     host: "10.253.239.4"
     api:
       key: "5f79a256e03c7fee0e"
       secret: "951bdbbc5e512b57926"

   cfile: '{{ playbook_dir }}/files/kingjoe_atc_tetration.json'
   app_name: 'PolicyPubApp'
   app_name: 'DAAnE'

  tasks:
    - name: get clusters for the specified application name
      debug:
        msg: '{{ item.id }} {{ item.name }} {{ item.description }} {{ item.consistent_uuid }}'
      loop: "{{ query('tetration_cluster', app_name, api_host=tet.host, api_cfile=cfile)  }}"

```
You encounter:
```bash
$ python ./playbook-parser.py ../test_tetration_clusters.yml
Traceback (most recent call last):
  File "./playbook-parser.py", line 68, in <module>
    main()
  File "./playbook-parser.py", line 54, in main
    playbook_data = yaml.load(file)
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 1469, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 1470, in construct_mapping
    if self.check_mapping_key(node, key_node, maptyp, key, value):
  File "/home/vagrant/.local/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "../test_tetration_clusters.yml", line 21, column 4
found duplicate key "app_name" with value "DAAnE" (original value: "PolicyPubApp")
  in "../test_tetration_clusters.yml", line 29, column 4

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

```

**Comment by nsthompson** [comment]
Solved by using ansible python modules for playbook parsing.
