### ISSUE TITLE
idontexist

### ISSUE THREAD

**Issue by joelwking** [nsthompson/ansible-collection-dependencies#4]
Consider handling IOErrors gracefully.
```
$ python ./playbook-parser.py ../idontexist.yml
Traceback (most recent call last):
  File "./playbook-parser.py", line 68, in <module>
    main()
  File "./playbook-parser.py", line 53, in main
    with open('{}'.format(playbook_path)) as file:
IOError: [Errno 2] No such file or directory: '../idontexist.yml'
``

**Comment by nsthompson** [comment]
Added file handling for missing files.
